# This TOML file is used to configure and display projects on my portfolio website.
# The following configurations are used to control how the content is presented on the site.
# Each project entry contains details such as the project name, description, technologies used,
# and the URL to the project.


[config]
display_name = "Youtube Downloader"
display = true
technologies = ['python', 'pytube']
